srun: Step created for StepId=41612383.128
srun: Step created for StepId=41612383.129
srun: Step created for StepId=41612383.130
srun: Step created for StepId=41612383.131
srun: Step created for StepId=41612383.132
srun: Step created for StepId=41612383.133
srun: Step created for StepId=41612383.134
srun: Step created for StepId=41612383.135
srun: Step created for StepId=41612383.136
srun: Step created for StepId=41612383.137
srun: Step created for StepId=41612383.138
srun: Step created for StepId=41612383.139
srun: Step created for StepId=41612383.140
srun: Step created for StepId=41612383.141
srun: Step created for StepId=41612383.142
srun: Step created for StepId=41612383.143
srun: Step created for StepId=41612383.144
srun: Step created for StepId=41612383.145
srun: Step created for StepId=41612383.146
srun: Step created for StepId=41612383.147
srun: Step created for StepId=41612383.148
srun: Step created for StepId=41612383.149
srun: Step created for StepId=41612383.150
srun: Step created for StepId=41612383.151
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.25
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.26
srun: Step created for StepId=41612383.152
srun: Step created for StepId=41612383.153
srun: Step created for StepId=41612383.154
srun: Step created for StepId=41612383.155
srun: Step created for StepId=41612383.156
srun: Step created for StepId=41612383.157
srun: Step created for StepId=41612383.158
srun: Step created for StepId=41612383.159
srun: Step created for StepId=41612383.160
srun: Step created for StepId=41612383.161
srun: Step created for StepId=41612383.162
srun: Step created for StepId=41612383.163
srun: Step created for StepId=41612383.164
srun: Step created for StepId=41612383.165
srun: Step created for StepId=41612383.166
srun: Step created for StepId=41612383.167
srun: Step created for StepId=41612383.168
srun: Step created for StepId=41612383.169
srun: Step created for StepId=41612383.170
srun: Step created for StepId=41612383.171
srun: Step created for StepId=41612383.172
srun: Step created for StepId=41612383.173
srun: Step created for StepId=41612383.174
srun: Step created for StepId=41612383.175
srun: Step created for StepId=41612383.176
srun: Step created for StepId=41612383.177
srun: Step created for StepId=41612383.178
srun: Step created for StepId=41612383.179
srun: Step created for StepId=41612383.180
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.60
srun: Step created for StepId=41612383.181
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
AssertionError
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.182
srun: Step created for StepId=41612383.183
srun: Step created for StepId=41612383.184
srun: Step created for StepId=41612383.185
srun: Step created for StepId=41612383.186
srun: Step created for StepId=41612383.187
srun: Step created for StepId=41612383.188
srun: Step created for StepId=41612383.189
srun: Step created for StepId=41612383.190
srun: Step created for StepId=41612383.191
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.76
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.68
srun: Step created for StepId=41612383.192
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.71
srun: Step created for StepId=41612383.193
srun: Step created for StepId=41612383.194
srun: Step created for StepId=41612383.195
srun: Step created for StepId=41612383.196
srun: Step created for StepId=41612383.197
srun: Step created for StepId=41612383.198
srun: Step created for StepId=41612383.199
srun: Step created for StepId=41612383.200
srun: Step created for StepId=41612383.201
srun: Step created for StepId=41612383.202
srun: Step created for StepId=41612383.203
srun: Step created for StepId=41612383.204
srun: Step created for StepId=41612383.205
srun: Step created for StepId=41612383.206
srun: Step created for StepId=41612383.207
srun: Step created for StepId=41612383.208
srun: Step created for StepId=41612383.209
srun: Step created for StepId=41612383.210
srun: Step created for StepId=41612383.211
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.212
srun: Step created for StepId=41612383.213
srun: Step created for StepId=41612383.214
srun: Step created for StepId=41612383.215
srun: Step created for StepId=41612383.216
srun: Step created for StepId=41612383.217
srun: Step created for StepId=41612383.218
srun: Step created for StepId=41612383.219
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.93
srun: Step created for StepId=41612383.220
srun: Step created for StepId=41612383.221
srun: Step created for StepId=41612383.222
srun: Step created for StepId=41612383.223
srun: Step created for StepId=41612383.224
srun: Step created for StepId=41612383.225
srun: Step created for StepId=41612383.226
srun: Step created for StepId=41612383.227
srun: Step created for StepId=41612383.228
srun: Step created for StepId=41612383.229
srun: Step created for StepId=41612383.230
srun: Step created for StepId=41612383.231
srun: Step created for StepId=41612383.232
srun: Step created for StepId=41612383.233
srun: Step created for StepId=41612383.234
srun: Step created for StepId=41612383.235
srun: Step created for StepId=41612383.236
srun: Step created for StepId=41612383.237
srun: Step created for StepId=41612383.238
srun: Step created for StepId=41612383.239
srun: Step created for StepId=41612383.240
srun: Step created for StepId=41612383.241
srun: Step created for StepId=41612383.242
srun: Step created for StepId=41612383.243
srun: Step created for StepId=41612383.244
srun: Step created for StepId=41612383.245
srun: Step created for StepId=41612383.246
srun: Step created for StepId=41612383.247
srun: Step created for StepId=41612383.248
srun: Step created for StepId=41612383.249
srun: Step created for StepId=41612383.250
srun: Step created for StepId=41612383.251
srun: Step created for StepId=41612383.252
srun: Step created for StepId=41612383.253
srun: Step created for StepId=41612383.254
srun: Step created for StepId=41612383.255
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.256
srun: Step created for StepId=41612383.257
srun: Step created for StepId=41612383.258
srun: Step created for StepId=41612383.259
srun: Step created for StepId=41612383.260
srun: Step created for StepId=41612383.261
srun: Step created for StepId=41612383.262
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.140
srun: Step created for StepId=41612383.263
srun: Step created for StepId=41612383.264
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.131
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.133
srun: Step created for StepId=41612383.265
srun: Step created for StepId=41612383.266
srun: Step created for StepId=41612383.267
srun: Step created for StepId=41612383.268
srun: Step created for StepId=41612383.269
srun: Step created for StepId=41612383.270
srun: Step created for StepId=41612383.271
srun: Step created for StepId=41612383.272
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid004463: task 0: Exited with exit code 2
srun: Terminating StepId=41612383.149
srun: Step created for StepId=41612383.273
srun: Step created for StepId=41612383.274
srun: Step created for StepId=41612383.275
srun: Step created for StepId=41612383.276
srun: Step created for StepId=41612383.277
srun: Step created for StepId=41612383.278
srun: Step created for StepId=41612383.279
srun: Step created for StepId=41612383.280
srun: Step created for StepId=41612383.281
srun: Step created for StepId=41612383.282
srun: Step created for StepId=41612383.283
srun: Step created for StepId=41612383.284
srun: Step created for StepId=41612383.285
srun: Step created for StepId=41612383.286
srun: Step created for StepId=41612383.287
srun: Step created for StepId=41612383.288
srun: Step created for StepId=41612383.289
srun: Step created for StepId=41612383.290
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.291
srun: Step created for StepId=41612383.292
srun: Step created for StepId=41612383.293
srun: Step created for StepId=41612383.294
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.295
srun: Step created for StepId=41612383.296
srun: Step created for StepId=41612383.297
srun: Step created for StepId=41612383.298
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.159
srun: Step created for StepId=41612383.299
srun: Step created for StepId=41612383.300
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.166
srun: Step created for StepId=41612383.301
srun: Step created for StepId=41612383.302
srun: Step created for StepId=41612383.303
srun: Step created for StepId=41612383.304
srun: Step created for StepId=41612383.305
srun: Step created for StepId=41612383.306
srun: Step created for StepId=41612383.307
srun: Step created for StepId=41612383.308
srun: Step created for StepId=41612383.309
srun: Step created for StepId=41612383.310
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: Step created for StepId=41612383.311
srun: Step created for StepId=41612383.312
srun: Step created for StepId=41612383.313
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.314
srun: Step created for StepId=41612383.315
srun: error: nid004463: task 0: Exited with exit code 2
srun: Terminating StepId=41612383.187
srun: Step created for StepId=41612383.316
srun: Step created for StepId=41612383.317
srun: Step created for StepId=41612383.318
srun: Step created for StepId=41612383.319
srun: Step created for StepId=41612383.320
srun: Step created for StepId=41612383.321
srun: Step created for StepId=41612383.322
srun: Step created for StepId=41612383.323
srun: Step created for StepId=41612383.324
srun: Step created for StepId=41612383.325
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.188
srun: Step created for StepId=41612383.326
srun: Step created for StepId=41612383.327
srun: Step created for StepId=41612383.328
srun: Step created for StepId=41612383.329
srun: Step created for StepId=41612383.330
srun: Step created for StepId=41612383.331
srun: Step created for StepId=41612383.332
srun: Step created for StepId=41612383.333
srun: Step created for StepId=41612383.334
srun: Step created for StepId=41612383.335
srun: Step created for StepId=41612383.336
srun: Step created for StepId=41612383.337
srun: Step created for StepId=41612383.338
srun: Step created for StepId=41612383.339
srun: Step created for StepId=41612383.340
srun: Step created for StepId=41612383.341
srun: Step created for StepId=41612383.342
srun: Step created for StepId=41612383.343
srun: Step created for StepId=41612383.344
srun: Step created for StepId=41612383.345
srun: Step created for StepId=41612383.346
srun: Step created for StepId=41612383.347
srun: Step created for StepId=41612383.348
srun: Step created for StepId=41612383.349
srun: Step created for StepId=41612383.350
srun: Step created for StepId=41612383.351
srun: Step created for StepId=41612383.352
srun: Step created for StepId=41612383.353
srun: Step created for StepId=41612383.354
srun: Step created for StepId=41612383.355
srun: Step created for StepId=41612383.356
srun: Step created for StepId=41612383.357
srun: Step created for StepId=41612383.358
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.359
srun: Step created for StepId=41612383.360
srun: Step created for StepId=41612383.361
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.362
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.226
srun: Step created for StepId=41612383.363
srun: Step created for StepId=41612383.364
srun: Step created for StepId=41612383.365
srun: Step created for StepId=41612383.366
srun: Step created for StepId=41612383.367
srun: Step created for StepId=41612383.368
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.243
srun: Step created for StepId=41612383.369
srun: Step created for StepId=41612383.370
srun: Step created for StepId=41612383.371
srun: Step created for StepId=41612383.372
srun: Step created for StepId=41612383.373
srun: Step created for StepId=41612383.374
srun: Step created for StepId=41612383.375
srun: Step created for StepId=41612383.376
srun: Step created for StepId=41612383.377
srun: Step created for StepId=41612383.378
srun: Step created for StepId=41612383.379
srun: Step created for StepId=41612383.380
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.236
srun: Step created for StepId=41612383.381
srun: Step created for StepId=41612383.382
srun: Step created for StepId=41612383.383
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41612383.384
srun: Step created for StepId=41612383.385
srun: Step created for StepId=41612383.386
srun: Step created for StepId=41612383.387
srun: Step created for StepId=41612383.388
srun: Step created for StepId=41612383.389
srun: Step created for StepId=41612383.390
srun: Step created for StepId=41612383.391
srun: Step created for StepId=41612383.392
srun: Step created for StepId=41612383.393
srun: Step created for StepId=41612383.394
srun: Step created for StepId=41612383.395
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.271
srun: Step created for StepId=41612383.396
srun: Step created for StepId=41612383.397
srun: Step created for StepId=41612383.398
srun: Step created for StepId=41612383.399
srun: Step created for StepId=41612383.400
srun: Step created for StepId=41612383.401
srun: Step created for StepId=41612383.402
srun: Step created for StepId=41612383.403
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.283
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.286
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid004463: task 0: Exited with exit code 2
srun: Terminating StepId=41612383.307
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.303
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.328
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.317
srun: error: nid004463: task 0: Exited with exit code 2
srun: Terminating StepId=41612383.357
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.363
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.377
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.396
srun: error: nid004463: task 0: Exited with exit code 1
srun: Terminating StepId=41612383.392
